### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ISheepp** [ISheepp/2023#2]
record todo list

**Comment by ISheepp** [comment]
~~- [ ] postman json 文件导出一下~~ postman 有同步功能

**Comment by ISheepp** [comment]
- [x] 赋能中心后端接口完成

**Comment by ISheepp** [comment]
- [x] 小站 容器缺陷修复
- [x] 编写sdk文档

**Comment by ISheepp** [comment]
- [ ] [arithmetic](https://github.com/lidangzzz/How-to-run) 实践ts语法
- [ ] [pancake合约解读](https://www.axihe.com/pancake-smart-contracts/masterchef/v1.html) pancake源码解读

**Comment by ISheepp** [comment]
- [x] 原型
- [x] 需求文档编写
- [x] 设计文档
- [x] 整理 how to defi 笔记

**Comment by ISheepp** [comment]
- [x] 需求文档修改
- [x] 给UI提原型
- [x] 分配设计文档编写内容
- [x] 提供在线文档：设计文档，写好文档格式
- [x] 需求文档编写（暂时不急）
- [x] 立项文档咨询编写（急）

**Comment by ISheepp** [comment]
- [x] 借贷 - on chain

**Comment by ISheepp** [comment]
- [x] 模型管理设计文档
- [x] 模型管理需求文档

## 重要
- [x] 立项ppt

**Comment by ISheepp** [comment]
Resume

- [ ] ThreadLocal
- [x] ACID
- [x] HashMap和HashTable
- [x] BeanFactory和ApplicationContext

**Comment by ISheepp** [comment]
- [x] MVCC的原理
- [x] mybatis
